// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3M4T7QTNG1OisjQU-LP5u14c0iPzAIis',
    appId: '1:427253646102:web:e80e03e8f53424de74c637',
    messagingSenderId: '427253646102',
    projectId: 'banky-cf930',
    authDomain: 'banky-cf930.firebaseapp.com',
    storageBucket: 'banky-cf930.appspot.com',
    measurementId: 'G-1ZCR6QMYKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdVBwUZ0VRrjQE0komHZmk1oReshOduSI',
    appId: '1:427253646102:android:f016b160c63578d774c637',
    messagingSenderId: '427253646102',
    projectId: 'banky-cf930',
    storageBucket: 'banky-cf930.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9CTqewO-RIMHsMGBs9kdlWD-QVmizzvI',
    appId: '1:427253646102:ios:ffa6925286b164b274c637',
    messagingSenderId: '427253646102',
    projectId: 'banky-cf930',
    storageBucket: 'banky-cf930.appspot.com',
    iosBundleId: 'com.banky.banky.banky',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9CTqewO-RIMHsMGBs9kdlWD-QVmizzvI',
    appId: '1:427253646102:ios:ffa6925286b164b274c637',
    messagingSenderId: '427253646102',
    projectId: 'banky-cf930',
    storageBucket: 'banky-cf930.appspot.com',
    iosBundleId: 'com.banky.banky.banky',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3M4T7QTNG1OisjQU-LP5u14c0iPzAIis',
    appId: '1:427253646102:web:7e0944f7a3de08a674c637',
    messagingSenderId: '427253646102',
    projectId: 'banky-cf930',
    authDomain: 'banky-cf930.firebaseapp.com',
    storageBucket: 'banky-cf930.appspot.com',
    measurementId: 'G-V13THBLPN1',
  );
}
